[package]
name = "iris-core"
version = "0.5.0"
edition = "2021"
description = "Iris — core runtime"
license = "AGPL-3.0"
repository = "https://github.com/SSL-ACTX/iris"

[dependencies]
num_cpus = "*"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "net", "io-util"] }
dashmap = "5"
parking_lot = "0.12"
bytes = "1.11.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
once_cell = "1"
crossbeam-channel = "0.5"
crossbeam-queue = "0.3.11"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "throughput"
harness = false
