name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Build (Base)
        run: cargo build --verbose --no-default-features

      - name: Run Tests (Base)
        env:
          RUST_BACKTRACE: 1
        run: cargo test --workspace --verbose --no-default-features

      - name: Run Tests (PyO3,Vortex)
        env:
          RUST_BACKTRACE: 1
        run: cargo test --workspace --verbose --no-default-features --features=pyo3,vortex
